# Generated by Django 5.1 on 2024-09-06 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='short_intto',
            new_name='short_intro',
        ),
    ]
