# Generated by Django 5.1 on 2024-09-13 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_review_owner_alter_review_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-vote_ratio', '-vote_total', 'title']},
        ),
    ]
